version: "3.9"

services:
  mydb:
    image: mydb:latest
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "gamernage"
    ports:
      - 5432:5432
    container_name: mydb
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql:z
    networks:
      - app_net
    # Password
    env_file:
      - ./docker/postgresql/.env
    restart: on-failure:5
networks:
  app_net:
    driver: "bridge"
volumes:
  db-store:
