services:
  - name: backend
    type: web
    env: rust
    buildCommand: |
      cd backend
      cargo build --release
    startCommand: |
      cd backend
      ./target/release/your_backend_executable
