name: Bump dependencies in Cargo.lock

on:
  schedule:
    - cron: "0 0 * * Sun"
  workflow_dispatch:

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo update
        run: cargo update 2>&1 | sed '/crates.io index/d' | tee -a cargo_update.log

      - name: Commit Cargo.lock
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b cargo_update
          git add Cargo.lock
          git commit -m "Weekly cargo update"

      - name: Push changes
        run: git push --set-upstream origin cargo_update

      - name: Create or update PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Weekly cargo update" --body "This PR updates dependencies in Cargo.lock" --head cargo_update
