name: Rust Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t mydb ./docker/postgresql/Dockerfile

      - name: Push Docker Image
        run: |
          docker tag mydb ${{ secrets.DOCKER_USERNAME }}/mydb:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mydb:latest

      - name: Set up PostgreSQL
        run: |
          docker compose -f docker-compose_dev.yml

      - name: Run initial SQL script
        run: |
          docker exec -i $(docker compose -f docker-compose_dev.yml ps -q postgres) psql -U secret -d gamernage -f /docker/postgres/init.sql

      - name: Move cache
        run: mv /cache/target .

      - name: Run tests
        run: mv .env.github .env && cargo test --features "integration" --verbose
        env:
          RUST_LOG: info
          DATABASE_URL: postgres://postgres:secret@postgres:5432/gamernage
